const macPanel = require('ti.macos.panels')
const ENTITLEMENTS_NOTE = 'Required: add <ios><entitlements>com.apple.security.files.user-selected.read-write</entitlements></ios> in tiapp.xml'

const win = Ti.UI.createWindow({
  layout: 'vertical',
  backgroundColor: '#ffffff'
})

const header = Ti.UI.createLabel({
  top: 24,
  left: 16,
  right: 16,
  color: '#111111',
  textAlign: Ti.UI.TEXT_ALIGNMENT_CENTER,
  text: 'ti.macos.panels example: Mac-only callback APIs.'
})

const entitlementsLabel = Ti.UI.createLabel({
  top: 8,
  left: 16,
  right: 16,
  color: '#9f1239',
  text: ENTITLEMENTS_NOTE,
  textAlign: Ti.UI.TEXT_ALIGNMENT_CENTER,
  font: { fontSize: 12, fontWeight: '600' }
})

const controls = Ti.UI.createScrollView({
  top: 12,
  left: 16,
  right: 16,
  width: Ti.UI.FILL,
  height: Ti.UI.FILL,
  layout: 'vertical',
  contentHeight: 'auto',
  showVerticalScrollIndicator: true
})

function createActionRow(title) {
  const row = Ti.UI.createView({
    top: 10,
    height: 44,
    borderWidth: 1,
    borderRadius: 8,
    width: Ti.UI.FILL,
    borderColor: '#d1d1d6',
    backgroundColor: '#f2f2f7'
  })

  const label = Ti.UI.createLabel({
    text: title,
    color: '#111111',
    textAlign: Ti.UI.TEXT_ALIGNMENT_CENTER,
    font: { fontSize: 15, fontWeight: '600' }
  })

  row.add(label)
  return row
}

function summarizeResult(methodName, result) {
  if (!result || typeof result !== 'object') {
    return `${methodName}: invalid response`
  }

  if (!result.success) {
    const code = result.code || 'ERR_UNKNOWN'
    const message = result.message || 'Unknown error'
    return `${methodName}: ${code} - ${message}`
  }

  if (Array.isArray(result.paths) && result.paths.length > 1) {
    return `${methodName}: ${JSON.stringify(result.paths)}`
  }

  if (result.path) {
    return `${methodName}: ${result.path}`
  }

  return `${methodName}: success`
}

function printResult(methodName, result) {
  const message = summarizeResult(methodName, result)
  infoLabel.text = message
  Ti.API.info(`[ti.macos.panels] ${message}`)
  Ti.API.info(`[ti.macos.panels] raw ${methodName}: ${JSON.stringify(result)}`)
}

function runAction(methodName, fn) {
  infoLabel.text = `${methodName}: opening...`
  Ti.API.info(`[ti.macos.panels] ${methodName} clicked`)

  setTimeout(() => {
    try {
      fn()
    } catch (error) {
      printResult(methodName, {
        success: false,
        code: 'ERR_UNKNOWN',
        message: error.message || String(error)
      })
    }
  }, 10)
}

const infoLabel = Ti.UI.createLabel({
  top: 16,
  left: 0,
  right: 0,
  color: '#111111',
  textAlign: Ti.UI.TEXT_ALIGNMENT_CENTER,
  text: 'Ready (check entitlements in tiapp.xml)'
})

const pickFolderButton = createActionRow('pickFolder(options, callback)')
const pickFileButton = createActionRow('pickFile(options, callback)')
const pickFilesButton = createActionRow('pickFiles(options, callback)')
const openDocumentButton = createActionRow('openDocument(options, callback)')
const openDocumentsButton = createActionRow('openDocuments(options, callback)')
const saveFileButton = createActionRow('saveFile(options, callback)')

pickFolderButton.addEventListener('click', () => {
  runAction('pickFolder', () => {
    macPanel.pickFolder({
      title: 'Choose a folder'
    }, (event) => {
      printResult('pickFolder', event)
    })
  })
})

pickFileButton.addEventListener('click', () => {
  runAction('pickFile', () => {
    macPanel.pickFile({
      title: 'Choose one file',
      allowedContentTypes: ['public.image']
    }, (event) => {
      printResult('pickFile', event)
    })
  })
})

pickFilesButton.addEventListener('click', () => {
  runAction('pickFiles', () => {
    macPanel.pickFiles({
      title: 'Choose multiple files',
      allowMultiple: true
    }, (event) => {
      printResult('pickFiles', event)
    })
  })
})

openDocumentButton.addEventListener('click', () => {
  runAction('openDocument', () => {
    macPanel.openDocument({
      title: 'Open one document',
      allowedContentTypes: ['public.text']
    }, (event) => {
      printResult('openDocument', event)
    })
  })
})

openDocumentsButton.addEventListener('click', () => {
  runAction('openDocuments', () => {
    macPanel.openDocuments({
      title: 'Open documents',
      allowedExtensions: ['txt', 'json']
    }, (event) => {
      printResult('openDocuments', event)
    })
  })
})

saveFileButton.addEventListener('click', () => {
  runAction('saveFile', () => {
    macPanel.saveFile({
      title: 'Save file',
      defaultName: 'new-file',
      defaultExtension: 'txt'
    }, (event) => {
      if (!event || !event.success || !event.path) {
        printResult('saveFile', event)
        return
      }

      try {
        const content = `Generated by ti.macos.panels example\n${new Date().toISOString()}\n`
        const file = Ti.Filesystem.getFile(event.path)
        file.write(content)

        printResult('saveFile', {
          success: true,
          code: null,
          message: 'File written successfully.',
          path: event.path,
          paths: [event.path]
        })
      } catch (error) {
        printResult('saveFile', {
          success: false,
          code: 'ERR_WRITE_PERMISSION_DENIED',
          message: error.message || String(error)
        })
      }
    })
  })
})

controls.add(pickFolderButton)
controls.add(pickFileButton)
controls.add(pickFilesButton)
controls.add(openDocumentButton)
controls.add(openDocumentsButton)
controls.add(saveFileButton)
controls.add(infoLabel)

win.add(header)
win.add(entitlementsLabel)
win.add(controls)
Ti.API.warn(`[ti.macos.panels] ${ENTITLEMENTS_NOTE}`)
win.open()
